2024-10-28 22:47:42,662 | WARNING | Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "C:\Python projeсt\homework_12\Lesson_12\test_12_4.py", line 21, in test_run
    run2 = Runner(5, 4)
           ^^^^^^^^^^^^
  File "C:\Python projeсt\homework_12\Lesson_12\rt_with_exeptions.py", line 6, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
2024-10-28 22:47:42,663 | WARNING | Неверная скорость для Runner
Traceback (most recent call last):
  File "C:\Python projeсt\homework_12\Lesson_12\test_12_4.py", line 11, in test_walk
    run1 = Runner('Михаил', -5)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Python projeсt\homework_12\Lesson_12\rt_with_exeptions.py", line 11, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -5
